# SAM Template :: Might eb able to delete later
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  GetWeather:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/get_weather
      Handler: get_weather
      Runtime: go1.x
      Architectures:
        - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          REGION: af-south-1
          SECRET_KEY: openWeatherApiKey
          OPEN_WEATHER_URL_KEY: openWeatherUrl
          SQS_QUEUE_NAME: get-dinner
  GetDinner:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/get_dinner
      Handler: get_dinner
      Runtime: go1.x
      Architectures:
        - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          REGION: af-south-1
      Events:
        SqsEvent:
          Type: SQS

  #MySqsQueue:
  #  Type: AWS::SQS::Queue

Outputs:
  GetWeather:
    Description: "Get weather Lambda Function ARN"
    Value: !GetAtt GetWeather.Arn

  GetDinner:
    Description: "Get diiner Lambda Function ARN"
    Value: !GetAtt GetDinner.Arn
